//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaModelContainer : DbContext
    {
        public CinemaModelContainer()
            : base("name=CinemaModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<MovieShow> MovieShow { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
