//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int Id { get; set; }
        public int Hall { get; set; }
        public int MovieShowId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Hall HallName { get; set; }
        public virtual MovieShow MovieShow { get; set; }
        public virtual Status Status { get; set; }
    }
}
